#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISCONVAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AUXWANCHAQ")]
	public partial class ValoresDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertNOTIFICADOR(NOTIFICADOR instance);
    partial void UpdateNOTIFICADOR(NOTIFICADOR instance);
    partial void DeleteNOTIFICADOR(NOTIFICADOR instance);
    #endregion
		
		public ValoresDataContext() : 
				base(global::SISCONVAL.Properties.Settings.Default.AUXWANCHAQConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ValoresDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ValoresDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ValoresDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ValoresDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ESTADORD> ESTADORD
		{
			get
			{
				return this.GetTable<ESTADORD>();
			}
		}
		
		public System.Data.Linq.Table<NOTIFICADOR> NOTIFICADOR
		{
			get
			{
				return this.GetTable<NOTIFICADOR>();
			}
		}
		
		public System.Data.Linq.Table<VALORESDET> VALORESDET
		{
			get
			{
				return this.GetTable<VALORESDET>();
			}
		}
		
		public System.Data.Linq.Table<VALORESGEN> VALORESGEN
		{
			get
			{
				return this.GetTable<VALORESGEN>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_CONTROLDEUDA_MODIFICARVALORCAB")]
		public int PA_CONTROLDEUDA_MODIFICARVALORCAB([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FAANIORESOLUCION", DbType="Int")] System.Nullable<int> fAANIORESOLUCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FNNRORESOLUCION", DbType="Int")] System.Nullable<int> fNNRORESOLUCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FAESTADOVALOR", DbType="NVarChar(1)")] string fAESTADOVALOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FMOBSERVACION", DbType="VarChar(255)")] string fMOBSERVACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FDFECHANOTIF", DbType="Date")] System.Nullable<System.DateTime> fDFECHANOTIF, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FDFECHAVENCI", DbType="Date")] System.Nullable<System.DateTime> fDFECHAVENCI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FNIDNOTIFICADOR", DbType="Int")] System.Nullable<int> fNIDNOTIFICADOR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fAANIORESOLUCION, fNNRORESOLUCION, fAESTADOVALOR, fMOBSERVACION, fDFECHANOTIF, fDFECHAVENCI, fNIDNOTIFICADOR);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ESTADORD")]
	public partial class ESTADORD
	{
		
		private string _facodestadord;
		
		private string _fadesestado;
		
		public ESTADORD()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facodestadord", DbType="VarChar(1)")]
		public string facodestadord
		{
			get
			{
				return this._facodestadord;
			}
			set
			{
				if ((this._facodestadord != value))
				{
					this._facodestadord = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fadesestado", DbType="VarChar(200)")]
		public string fadesestado
		{
			get
			{
				return this._fadesestado;
			}
			set
			{
				if ((this._fadesestado != value))
				{
					this._fadesestado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NOTIFICADOR")]
	public partial class NOTIFICADOR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FACODNOTI;
		
		private string _FANOMNOTR;
		
		private string _FANOMCORT;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFACODNOTIChanging(int value);
    partial void OnFACODNOTIChanged();
    partial void OnFANOMNOTRChanging(string value);
    partial void OnFANOMNOTRChanged();
    partial void OnFANOMCORTChanging(string value);
    partial void OnFANOMCORTChanged();
    #endregion
		
		public NOTIFICADOR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FACODNOTI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FACODNOTI
		{
			get
			{
				return this._FACODNOTI;
			}
			set
			{
				if ((this._FACODNOTI != value))
				{
					this.OnFACODNOTIChanging(value);
					this.SendPropertyChanging();
					this._FACODNOTI = value;
					this.SendPropertyChanged("FACODNOTI");
					this.OnFACODNOTIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FANOMNOTR", DbType="VarChar(200)")]
		public string FANOMNOTR
		{
			get
			{
				return this._FANOMNOTR;
			}
			set
			{
				if ((this._FANOMNOTR != value))
				{
					this.OnFANOMNOTRChanging(value);
					this.SendPropertyChanging();
					this._FANOMNOTR = value;
					this.SendPropertyChanged("FANOMNOTR");
					this.OnFANOMNOTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FANOMCORT", DbType="VarChar(25)")]
		public string FANOMCORT
		{
			get
			{
				return this._FANOMCORT;
			}
			set
			{
				if ((this._FANOMCORT != value))
				{
					this.OnFANOMCORTChanging(value);
					this.SendPropertyChanging();
					this._FANOMCORT = value;
					this.SendPropertyChanged("FANOMCORT");
					this.OnFANOMCORTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VALORESDET")]
	public partial class VALORESDET
	{
		
		private string _FAANIORESOLUCION;
		
		private int _FNNRORESOLUCION;
		
		private string _FAANIOTRIBU;
		
		private string _FAIDCIUDADANO;
		
		private string _FAAPELLIDOSYNOMBRES;
		
		private string _FADIRECCION;
		
		private System.Nullable<decimal> _FNBASEIMPDEC;
		
		private System.Nullable<decimal> _FNBASEIMPFISC;
		
		private System.Nullable<decimal> _FNINSOLUTODEC;
		
		private System.Nullable<decimal> _FNINSOLUTOFISC;
		
		private decimal _FNIMPPAGADO;
		
		private decimal _FNIMPPENDIENTE;
		
		private decimal _FNFACTOR;
		
		private decimal _FNTIM;
		
		private System.Nullable<decimal> _FNMORA;
		
		private System.Nullable<decimal> _FNGASADMIN;
		
		private System.Nullable<decimal> _FNTOTALRD;
		
		private string _FAESTADORD;
		
		private System.DateTime _FDFECHAGENERACION;
		
		public VALORESDET()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAANIORESOLUCION", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string FAANIORESOLUCION
		{
			get
			{
				return this._FAANIORESOLUCION;
			}
			set
			{
				if ((this._FAANIORESOLUCION != value))
				{
					this._FAANIORESOLUCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNNRORESOLUCION", DbType="Int NOT NULL")]
		public int FNNRORESOLUCION
		{
			get
			{
				return this._FNNRORESOLUCION;
			}
			set
			{
				if ((this._FNNRORESOLUCION != value))
				{
					this._FNNRORESOLUCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAANIOTRIBU", DbType="NVarChar(4)")]
		public string FAANIOTRIBU
		{
			get
			{
				return this._FAANIOTRIBU;
			}
			set
			{
				if ((this._FAANIOTRIBU != value))
				{
					this._FAANIOTRIBU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAIDCIUDADANO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FAIDCIUDADANO
		{
			get
			{
				return this._FAIDCIUDADANO;
			}
			set
			{
				if ((this._FAIDCIUDADANO != value))
				{
					this._FAIDCIUDADANO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAAPELLIDOSYNOMBRES", DbType="NVarChar(100)")]
		public string FAAPELLIDOSYNOMBRES
		{
			get
			{
				return this._FAAPELLIDOSYNOMBRES;
			}
			set
			{
				if ((this._FAAPELLIDOSYNOMBRES != value))
				{
					this._FAAPELLIDOSYNOMBRES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FADIRECCION", DbType="NVarChar(100)")]
		public string FADIRECCION
		{
			get
			{
				return this._FADIRECCION;
			}
			set
			{
				if ((this._FADIRECCION != value))
				{
					this._FADIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNBASEIMPDEC", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> FNBASEIMPDEC
		{
			get
			{
				return this._FNBASEIMPDEC;
			}
			set
			{
				if ((this._FNBASEIMPDEC != value))
				{
					this._FNBASEIMPDEC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNBASEIMPFISC", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> FNBASEIMPFISC
		{
			get
			{
				return this._FNBASEIMPFISC;
			}
			set
			{
				if ((this._FNBASEIMPFISC != value))
				{
					this._FNBASEIMPFISC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNINSOLUTODEC", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> FNINSOLUTODEC
		{
			get
			{
				return this._FNINSOLUTODEC;
			}
			set
			{
				if ((this._FNINSOLUTODEC != value))
				{
					this._FNINSOLUTODEC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNINSOLUTOFISC", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> FNINSOLUTOFISC
		{
			get
			{
				return this._FNINSOLUTOFISC;
			}
			set
			{
				if ((this._FNINSOLUTOFISC != value))
				{
					this._FNINSOLUTOFISC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNIMPPAGADO", DbType="Decimal(18,2) NOT NULL")]
		public decimal FNIMPPAGADO
		{
			get
			{
				return this._FNIMPPAGADO;
			}
			set
			{
				if ((this._FNIMPPAGADO != value))
				{
					this._FNIMPPAGADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNIMPPENDIENTE", DbType="Decimal(18,2) NOT NULL")]
		public decimal FNIMPPENDIENTE
		{
			get
			{
				return this._FNIMPPENDIENTE;
			}
			set
			{
				if ((this._FNIMPPENDIENTE != value))
				{
					this._FNIMPPENDIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNFACTOR", DbType="Decimal(18,2) NOT NULL")]
		public decimal FNFACTOR
		{
			get
			{
				return this._FNFACTOR;
			}
			set
			{
				if ((this._FNFACTOR != value))
				{
					this._FNFACTOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNTIM", DbType="Decimal(18,2) NOT NULL")]
		public decimal FNTIM
		{
			get
			{
				return this._FNTIM;
			}
			set
			{
				if ((this._FNTIM != value))
				{
					this._FNTIM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNMORA", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> FNMORA
		{
			get
			{
				return this._FNMORA;
			}
			set
			{
				if ((this._FNMORA != value))
				{
					this._FNMORA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNGASADMIN", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> FNGASADMIN
		{
			get
			{
				return this._FNGASADMIN;
			}
			set
			{
				if ((this._FNGASADMIN != value))
				{
					this._FNGASADMIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNTOTALRD", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> FNTOTALRD
		{
			get
			{
				return this._FNTOTALRD;
			}
			set
			{
				if ((this._FNTOTALRD != value))
				{
					this._FNTOTALRD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAESTADORD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string FAESTADORD
		{
			get
			{
				return this._FAESTADORD;
			}
			set
			{
				if ((this._FAESTADORD != value))
				{
					this._FAESTADORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDFECHAGENERACION", DbType="DateTime2 NOT NULL")]
		public System.DateTime FDFECHAGENERACION
		{
			get
			{
				return this._FDFECHAGENERACION;
			}
			set
			{
				if ((this._FDFECHAGENERACION != value))
				{
					this._FDFECHAGENERACION = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VALORESGEN")]
	public partial class VALORESGEN
	{
		
		private int _FAANIORESOLUCION;
		
		private string _FATRIBUTO;
		
		private int _FNNRORESOLUCION;
		
		private string _FAIDCIUDADANO;
		
		private string _FAAPELLIDOSYNOMBRES;
		
		private string _FADIRECCION;
		
		private string _FAREFERENCIA;
		
		private string _FACODSECTOR;
		
		private string _FAESTADOVALOR;
		
		private string _FMOBSERVACION;
		
		private int _FADESDE;
		
		private System.Nullable<int> _FAHASTA;
		
		private System.Nullable<System.DateTime> _FDFECHAEMISION;
		
		private System.Nullable<System.DateTime> _FDFECHANOTIF;
		
		private System.Nullable<System.DateTime> _FDFECHAVENCI;
		
		private System.Nullable<System.DateTime> _FDFECHAENVIO;
		
		private System.Nullable<System.DateTime> _FDFECHAMODIF;
		
		private System.Nullable<int> _FNIDNOTIFICADOR;
		
		private System.Nullable<decimal> _FNBASEIMPONIBLE;
		
		private System.Nullable<decimal> _FNTOTALVALOR;
		
		public VALORESGEN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAANIORESOLUCION", DbType="Int NOT NULL")]
		public int FAANIORESOLUCION
		{
			get
			{
				return this._FAANIORESOLUCION;
			}
			set
			{
				if ((this._FAANIORESOLUCION != value))
				{
					this._FAANIORESOLUCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FATRIBUTO", DbType="NVarChar(50)")]
		public string FATRIBUTO
		{
			get
			{
				return this._FATRIBUTO;
			}
			set
			{
				if ((this._FATRIBUTO != value))
				{
					this._FATRIBUTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNNRORESOLUCION", DbType="Int NOT NULL")]
		public int FNNRORESOLUCION
		{
			get
			{
				return this._FNNRORESOLUCION;
			}
			set
			{
				if ((this._FNNRORESOLUCION != value))
				{
					this._FNNRORESOLUCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAIDCIUDADANO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FAIDCIUDADANO
		{
			get
			{
				return this._FAIDCIUDADANO;
			}
			set
			{
				if ((this._FAIDCIUDADANO != value))
				{
					this._FAIDCIUDADANO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAAPELLIDOSYNOMBRES", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string FAAPELLIDOSYNOMBRES
		{
			get
			{
				return this._FAAPELLIDOSYNOMBRES;
			}
			set
			{
				if ((this._FAAPELLIDOSYNOMBRES != value))
				{
					this._FAAPELLIDOSYNOMBRES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FADIRECCION", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string FADIRECCION
		{
			get
			{
				return this._FADIRECCION;
			}
			set
			{
				if ((this._FADIRECCION != value))
				{
					this._FADIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAREFERENCIA", DbType="NVarChar(255)")]
		public string FAREFERENCIA
		{
			get
			{
				return this._FAREFERENCIA;
			}
			set
			{
				if ((this._FAREFERENCIA != value))
				{
					this._FAREFERENCIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FACODSECTOR", DbType="NVarChar(50)")]
		public string FACODSECTOR
		{
			get
			{
				return this._FACODSECTOR;
			}
			set
			{
				if ((this._FACODSECTOR != value))
				{
					this._FACODSECTOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAESTADOVALOR", DbType="NVarChar(50)")]
		public string FAESTADOVALOR
		{
			get
			{
				return this._FAESTADOVALOR;
			}
			set
			{
				if ((this._FAESTADOVALOR != value))
				{
					this._FAESTADOVALOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FMOBSERVACION", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string FMOBSERVACION
		{
			get
			{
				return this._FMOBSERVACION;
			}
			set
			{
				if ((this._FMOBSERVACION != value))
				{
					this._FMOBSERVACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FADESDE", DbType="Int NOT NULL")]
		public int FADESDE
		{
			get
			{
				return this._FADESDE;
			}
			set
			{
				if ((this._FADESDE != value))
				{
					this._FADESDE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAHASTA", DbType="Int")]
		public System.Nullable<int> FAHASTA
		{
			get
			{
				return this._FAHASTA;
			}
			set
			{
				if ((this._FAHASTA != value))
				{
					this._FAHASTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDFECHAEMISION", DbType="Date")]
		public System.Nullable<System.DateTime> FDFECHAEMISION
		{
			get
			{
				return this._FDFECHAEMISION;
			}
			set
			{
				if ((this._FDFECHAEMISION != value))
				{
					this._FDFECHAEMISION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDFECHANOTIF", DbType="Date")]
		public System.Nullable<System.DateTime> FDFECHANOTIF
		{
			get
			{
				return this._FDFECHANOTIF;
			}
			set
			{
				if ((this._FDFECHANOTIF != value))
				{
					this._FDFECHANOTIF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDFECHAVENCI", DbType="Date")]
		public System.Nullable<System.DateTime> FDFECHAVENCI
		{
			get
			{
				return this._FDFECHAVENCI;
			}
			set
			{
				if ((this._FDFECHAVENCI != value))
				{
					this._FDFECHAVENCI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDFECHAENVIO", DbType="Date")]
		public System.Nullable<System.DateTime> FDFECHAENVIO
		{
			get
			{
				return this._FDFECHAENVIO;
			}
			set
			{
				if ((this._FDFECHAENVIO != value))
				{
					this._FDFECHAENVIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDFECHAMODIF", DbType="Date")]
		public System.Nullable<System.DateTime> FDFECHAMODIF
		{
			get
			{
				return this._FDFECHAMODIF;
			}
			set
			{
				if ((this._FDFECHAMODIF != value))
				{
					this._FDFECHAMODIF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNIDNOTIFICADOR", DbType="Int")]
		public System.Nullable<int> FNIDNOTIFICADOR
		{
			get
			{
				return this._FNIDNOTIFICADOR;
			}
			set
			{
				if ((this._FNIDNOTIFICADOR != value))
				{
					this._FNIDNOTIFICADOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNBASEIMPONIBLE", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> FNBASEIMPONIBLE
		{
			get
			{
				return this._FNBASEIMPONIBLE;
			}
			set
			{
				if ((this._FNBASEIMPONIBLE != value))
				{
					this._FNBASEIMPONIBLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNTOTALVALOR", DbType="Money")]
		public System.Nullable<decimal> FNTOTALVALOR
		{
			get
			{
				return this._FNTOTALVALOR;
			}
			set
			{
				if ((this._FNTOTALVALOR != value))
				{
					this._FNTOTALVALOR = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
